<?php  

$dataTranslations = {
    en: {
  
        n1: "Home",
        "n2": "About",
        "n3": "Devices",
        "n4": "Career",
        "m1": "Home",
        "m2": "About",
        "m3": "Devices",
        "m4": "Career",
        "lan": "EN",
        "welcome": "Welcome to SMARTRACK",
        "description": "Transform asset management with real-time tracking, empowering you to make informed decisions and boost productivity. 'Track, Monitor, Protect'.",
        "start": "Get Started",
        "trans": "Transforming Asset Management in Cameroon",
        "camer": "Cameroon has over 38,000 companies across 25 sectors, with transportation and warehousing being the most prevalent, featuring 166 companies. The number of registered vehicles in Cameroon is steadily increasing.",
        "offer":"The Smartfleet offering targets companies from various sectors, such as banks and transport firms, that operate a minimum of five vehicles and require enhanced safety and efficiency. It is also available to individuals concerned about vehicle security.",
        "quote":"Get a quote",
        "get":"Get a quote",
        "request":"Request for fleet tracking or smart solution services, and we'll provide fast, reliable and customized solutions to fit your requirements.",
        "sent":"quote request has been sent successfully. Thank you!",
        "benefit":"Benefits of Smartrack",
        "stay":"Stay connected, stay secured and stay in control with Smartrack",
        "real":"Real-time tracking and monitoring",
        "monitor":"Monitor your fleet instantly, providing live updates and alerts. Stay in control with up-to-the-minute data on vehicle locations, security status, and more.",
        "con":"Stay connected and stay protected",
        "langu":"EN",
        "pro":"Stay connected and stay protected with smartrack's real-time monitoring and advanced security features, ensuring you're always in control of your fleet and home.",
        "two":"24/7 Accessability",
        "man":"Manage and mornitor your fleet or home security anytime, anywhere, ensuring constant vigilance and control.",
        "rel":"Reliable customer support",
        "acc":"Access dedicated support whenever you need smartrack, ensuring that you get the best out of smartTracks solutions.",
        "form":"Transform your fleet and security with our innovative, customized services.",
        "ft":"FLeet Tracking",
        "tor":"Monitor your enter fleet in real-time with our advanced GPS tracking system. Optimize routes, reduce fuel consumption, and inprove overall efficiency while staying informed of vehicle locations and driver behaviour.",
        "veh":"Vehicle Monitoring",
        "gain":"Gain insights into your vehicles' performance with detailed monitoring tools. Track speed, fuel usage, and maintainance needs to keep your fleet running and smoothly avoid disruptions.",
        "rity":"Security",
        "tect":"Protect your assets with our state-of-the-art security systems. From surveillance cameras to alarm systems, ensure your property is safe and secure with real-time alerts and remote monitoring capabilities.",
        "fire":"Fire Detection",
        "ahead":"Stay ahead of potential fire detection hazards with our advanced fire detection systems. Receive immediate notifications of smoke or heat, allowing for rapid response and reducing the risk of damage.",
        "remote":"Remote-Controlled Access",
        "entry":"Manage your entry points remotedly with our smart door locks. Control access from anywhere monitor who enters and exits, and enhance security with keyless entry options.",
        "hen":"Conprehensive Reporting",
        "detail":"Access detailed reports and security systems. Track performance metrics, identity trends, and make data-driven decisions to improve operationa efficiency and safety.",
        "adv":"Advanced Solutions for Modern Security",
        "empower":"Smartrack empowers you with real-time fleet monitoring and advanced solutions. Stay connected to your assets at all times with our seamless tracking system, Designed to reduce risk and enhance control.",
        "auto":"Smart Automation",
        "routine":"Automate routine tasks and enhace efficiency with intelligent solutions tailored to your needs.",
        "geo":"Geofecing  Alerts",
        "set":"Set virtual boundaries and receive alerts when vehicles or assets  move beyond designated areas.",
        "driven":"Data-Driven Insights",
        "rage":"Leverage powerfull data analytics to improve operational descisions and optimize performance.",
        "han":"Ehanced Visibility",
        "visi":"Gain complete visibility over your assets and operations, helping you stay informed and in control.",
        "time":"Real-Time GPS Tracking",
        "driver":"Driver Behavior Monitoring",
        "advan":"Advanced Security Intergration",
        "custom":"Customizable Reporting",
        "sgps":"Smartrack GPS",
        "gtrack":"Our GPS tracking allows you to monitor your fleet and assets around the clock. Whether you're managing vehicles or securing property, our GPS technology gives you precise, up-to-the-minute information, ensuring complete visibility and peace of mind.",
        "livel":"Live Location Updates",
        "efi":"Improved Efficiency",
        "ins":"Instant Alert",
        "dbe":"Driver Behaviour",
        "with":"With Smartrack's driver Behaviour monitoring, you can enhance the safety and efficiency of your fleet. Analyze driver pattern such as speeding and harsh braking.",
        "safety":"Safety Tracking",
        "fuel":"Fuel Efficiency",
        "perf":"Performance Insight",
        "advanced":"Advanced Security",
        "scam":"Smart Cameras",
        "control":"Remote Acess Control",
        "alerts":"Immediate Alerts",
        "inter":"Smartrack offers advanced security intergration, combining multiple technologies to safeguard your assets. Seamlessly connect smart cameras, alarms, and door locks for comprehensive protection, giving you real-time control and instant alerts.",
        "customreport":"Customizable Reporting",
        "reporttools":"Smartrack reporting tools let you genarate tailored report based on your specific needs. whether you're tracking fleet performance or analyzing security events, you'll gain insights that help you make data-driven decisons and optimize your operation.",
        "tailor":"Tailored Data",
        "decision":"Improved Decision Making",
        "automated":"Automated Reports",
        "testimony":"Testimonials",
        "here":"Here is what our customers say about their experience with smartrack",
        "blog":"Recent Blog Posts",
        "ho":"Home",
    "ab":"About us",
    "carr":"Career",
    "terms":"Terms of service",
    "pri":"Privacy policy",
    "fmanage":"Fleet Management",
    "fumanage":"Fuel Management",
    "firedet":"Fire Detection System",
    "network":"Network and Security",
    "vsurv":"Video Surveillance",
    "timeand":"Time and Attendance Management",
    "access":"Access Control",
    "abo":"About",
    "hom":"Home",
    "abbo":"About",
    "abou":"About Us",
    "since":"Since 2007",
    "who":"Who Are We ?",
    "lead":"Smartrack Africa is a leading provider of advanced tracking and protection services for vehicles and valuable assets. The company specializes in theft prevention, real-time vehicle location monitoring, and comprehensive asset tracking capabilities. Smartrack's solutions leverage GPS, telematics, and wireless technologies to deliver enhanced security, improve fleet management, and provide detailed insights into the status and movements of vehicles and equipment. By offering a comprehensive platform that combines security systems, real-time tracking, and customizable reporting, Smartrack helps businesses and individuals optimize the management and protection of their mobile resources and physical assets.",
    "watch":"Watch Video",
    "stats":"Stats",
    "commitment":"Smartrack's commitment to excellence is reflected in these powerful statistics. See for yourself the impact we deliver.",
    "happy":"Happy Clients",
    "proj":"Projects",
    "hours":"Hours Of Support",
    "hard":"Hard Workers",
    "team":"Team",
    "strong":"A strong team is the foundation of our success - meet the experts behind Smartrack's industry-leading solutions."
      
  },
  
"fr": {
  
        n1: "Accueil",
        "n2": "À propos",
        "n3": "Appareils",
        "n4": "Carrière",
        "m1": "Accueil",
        "m2": "À propos",
        "m3": "Appareils",
        "m4": "Carrière",
        "lan": "FR",
        "welcome": "Bienvenue chez SMARTRACK",
        "description": "Transformez la gestion des actifs avec un suivi en temps réel, vous permettant de prendre des décisions éclairées et d'augmenter la productivité. 'Suivez, Surveillez, Protégez'.",
        "start": "Commencer",
        "trans": "Transformer la gestion des actifs au Cameroun",
        "camer": "Le Cameroun compte plus de 38 000 entreprises dans 25 secteurs, le transport et l'entreposage étant les plus répandus, avec 166 entreprises. Le nombre de véhicules enregistrés au Cameroun augmente régulièrement.",
        "offer": "L'offre Smartfleet cible les entreprises de divers secteurs, comme les banques et les sociétés de transport, qui exploitent un minimum de cinq véhicules et nécessitent une sécurité et une efficacité accrues. Elle est également disponible pour les particuliers soucieux de la sécurité de leur véhicule.",
        "quote": "Obtenir un devis",
        "get": "Obtenir un devis",
        "request": "Demandez un suivi de flotte ou des services de solutions intelligentes, et nous fournirons des solutions rapides, fiables et personnalisées pour répondre à vos besoins.",
        "sent": "La demande de devis a été envoyée avec succès. Merci !",
        "benefit": "Avantages de Smartrack",
        "stay": "Restez connecté, sécurisé et en contrôle avec Smartrack",
        "real": "Suivi et surveillance en temps réel",
        "monitor": "Surveillez votre flotte instantanément, en fournissant des mises à jour et des alertes en direct. Restez en contrôle avec des données à jour sur les emplacements des véhicules, l'état de sécurité, et plus encore.",
        "con": "Restez connecté et protégé",
        "langu": "FR",
        "pro": "Restez connecté et protégé avec le suivi en temps réel de Smartrack et ses fonctionnalités avancées de sécurité, vous assurant que vous êtes toujours en contrôle de votre flotte et de votre domicile.",
        "two": "Accessibilité 24/7",
        "man": "Gérez et surveillez votre flotte ou la sécurité de votre maison à tout moment, n'importe où, en assurant une vigilance et un contrôle constants.",
        "rel": "Support client fiable",
        "acc": "Accédez à un support dédié chaque fois que vous avez besoin de Smartrack, en vous assurant que vous tirez le meilleur parti des solutions de Smartrack.",
        "form": "Transformez votre flotte et votre sécurité avec nos services innovants et personnalisés.",
        "ft": "Suivi de flotte",
        "tor": "Surveillez l'ensemble de votre flotte en temps réel avec notre système de suivi GPS avancé. Optimisez les itinéraires, réduisez la consommation de carburant et améliorez l'efficacité globale tout en restant informé des emplacements des véhicules et du comportement des conducteurs.",
        "veh": "Suivi de véhicules",
        "gain": "Obtenez des informations sur les performances de vos véhicules avec des outils de suivi détaillés. Suivez la vitesse, la consommation de carburant et les besoins en maintenance pour garder votre flotte opérationnelle et éviter les interruptions.",
        "rity": "Sécurité",
        "tect": "Protégez vos actifs avec nos systèmes de sécurité à la pointe de la technologie. Des caméras de surveillance aux systèmes d'alarme, assurez-vous que votre propriété est sûre et sécurisée avec des alertes en temps réel et des capacités de surveillance à distance.",
        "fire": "Détection d'incendie",
        "ahead": "Restez en avance sur les dangers potentiels de détection d'incendie avec nos systèmes avancés de détection d'incendie. Recevez des notifications immédiates de fumée ou de chaleur, permettant une réponse rapide et réduisant le risque de dommages.",
        "remote": "Accès à distance",
        "entry": "Gérez vos points d'entrée à distance avec nos serrures de porte intelligentes. Contrôlez l'accès depuis n'importe où, surveillez qui entre et sort, et améliorez la sécurité avec des options d'entrée sans clé.",
        "hen": "Rapports complets",
        "detail": "Accédez à des rapports détaillés et à des systèmes de sécurité. Suivez les indicateurs de performance, identifiez les tendances et prenez des décisions basées sur les données pour améliorer l'efficacité opérationnelle et la sécurité.",
        "adv": "Solutions avancées pour la sécurité moderne",
        "empower": "Smartrack vous donne les moyens avec un suivi de flotte en temps réel et des solutions avancées. Restez connecté à vos actifs à tout moment avec notre système de suivi transparent, conçu pour réduire les risques et améliorer le contrôle.",
        "auto": "Automatisation intelligente",
        "routine": "Automatisez les tâches routinières et améliorez l'efficacité avec des solutions intelligentes adaptées à vos besoins.",
        "geo": "Alertes de géorepérage",
        "set": "Définissez des frontières virtuelles et recevez des alertes lorsque des véhicules ou des actifs dépassent les zones désignées.",
        "driven": "Informations basées sur les données",
        "rage": "Exploitez la puissance de l'analyse de données pour améliorer les décisions opérationnelles et optimiser les performances.",
        "han": "Visibilité améliorée",
        "visi": "Obtenez une visibilité complète sur vos actifs et vos opérations, vous aidant à rester informé et en contrôle.",
        "time": "Suivi GPS en temps réel",
        "driver": "Suivi du comportement des conducteurs",
        "advan": "Intégration de sécurité avancée",
        "custom": "Rapports personnalisables",
        "sgps": "Smartrack GPS",
        "gtrack": "Notre suivi GPS vous permet de surveiller votre flotte et vos actifs 24 heures sur 24. Que vous gériez des véhicules ou que vous sécurisiez des biens, notre technologie GPS vous fournit des informations précises et à jour, assurant une visibilité complète et une tranquillité d'esprit.",
        "livel": "Mises à jour de localisation en direct",
        "efi": "Efficacité améliorée",
        "ins": "Alerte instantanée",
        "dbe": "Comportement du conducteur",
        "with": "Avec le suivi du comportement des conducteurs de Smartrack, vous pouvez améliorer la sécurité et l'efficacité de votre flotte. Analysez les comportements des conducteurs tels que l'excès de vitesse et les freinages brusques.",
        "safety": "Suivi de la sécurité",
        "fuel": "Efficacité énergétique",
        "perf": "Aperçu des performances",
        "advanced": "Sécurité avancée",
        "scam": "Caméras intelligentes",
        "control": "Contrôle d'accès à distance",
        "alerts": "Alertes immédiates",
        "inter": "Smartrack offre une intégration de sécurité avancée, combinant plusieurs technologies pour protéger vos actifs. Connectez sans effort des caméras intelligentes, des alarmes et des serrures de porte pour une protection complète, vous donnant un contrôle en temps réel et des alertes instantanées.",
        "customreport": "Rapports personnalisables",
        "reporttools": "Les outils de reporting de Smartrack vous permettent de générer des rapports adaptés à vos besoins spécifiques. Que vous suiviez les performances de la flotte ou analysiez des événements de sécurité, vous obtiendrez des informations qui vous aideront à prendre des décisions basées sur les données et à optimiser vos opérations.",
        "tailor": "Données sur mesure",
        "decision": "Amélioration de la prise de décision",
        "automated": "Rapports automatisés",
        "testimony": "Témoignages",
        "here": "Voici ce que nos clients disent de leur expérience avec Smartrack",
        "blog": "Articles de blog récents",
        "ho": "Accueil",
        "ab": "À propos de nous",
        "carr": "Carrière",
        "terms": "Conditions de service",
        "pri": "Politique de confidentialité",
        "fmanage": "Gestion de flotte",
        "fumanage": "Gestion du carburant",
        "firedet": "Système de détection d'incendie",
        "network": "Réseau et sécurité",
        "vsurv": "Surveillance vidéo",
        "timeand": "Gestion du temps et des présences",
        "access": "Contrôle d'accès",
        "abo": "À propos",
        "hom": "Accueil",
        "abbo": "À propos",
        "abou": "À propos de nous",
        "since": "Depuis 2007",
        "who": "Qui sommes-nous ?",
        "lead": "Smartrack Afrique est un fournisseur leader de services avancés de suivi et de protection pour les véhicules et les biens précieux. L'entreprise se spécialise dans la prévention du vol, le suivi en temps réel de l'emplacement des véhicules et des capacités de suivi des actifs. Les solutions de Smartrack exploitent les technologies GPS, télématiques et sans fil pour offrir une sécurité renforcée, améliorer la gestion de flotte et fournir des informations détaillées sur l'état et les mouvements des véhicules et de l'équipement. En offrant une plateforme complète qui combine des systèmes de sécurité, un suivi en temps réel et des rapports personnalisables, Smartrack aide les entreprises et les particuliers à optimiser la gestion et la protection de leurs ressources mobiles et de leurs actifs physiques.",
        "watch": "Regarder la vidéo",
        "stats": "Statistiques",
        "commitment": "L'engagement de Smartrack envers l'excellence se reflète dans ces statistiques puissantes. Voyez par vous-même l'impact que nous livrons.",
        "happy": "Clients satisfaits",
        "proj": "Projets",
        "hours": "Heures de support",
        "hard": "Travailleurs acharnés",
        "team": "Équipe",
        "strong": "Une équipe solide est la base de notre succès - rencontrez les experts derrière les solutions de pointe de Smartrack." 
  }
}

$dataTranslations =    json_encode($dataTranslations)
?>